filesets:
  default:
    include:
      - ".watchcode.yaml"
      - "*.nim"
    exclude:
      - ".watchcode.log"
    exclude_gitignore: false
    match_mode: "gitlike"

tasks:
  default:
    fileset: default
    commands:
      #- "nim -r c ./dev/experiment_1.nim"
      #- "nim -r c ./dev/debug_1.nim"
      #- "nim -r c ./tests/test_unwrap.nim"

      #- "nim -r c ./tests/standard_class/test_draft.nim"
      #- "nim -r c ./tests/standard_class/test_basic_3.nim"
      #- "nim -r c ./tests/standard_class/testerror_base_calls_1.nim"
      - "nim -r c ./tests/standard_class/test_abstract_1.nim"
      #- "nim -r c ./tests/standard_class/test_template_accessors.nim"

      #- "nim -r c ./tests/test_basic_1.nim"
      #- "nim -r c ./tests/test_inheritance_chain.nim"
      #- "nim -r c ./tests/test_overload.nim"
      #- "nim -r c ./tests/test_empty_ctor.nim"
      #- "nim -r c ./tests/test_base_calls.nim"
      #- "nim -r c ./tests/test_abstract_2.nim"
      #- "nim -r c ./tests/test_generic_constructor.nim"
      #- "nim -r c ./tests/test_generics_1.nim"
      #- "nim -r c ./tests/test_ctor_calls_2.nim"
      #- "nim -r c ./tests/test_ctor_post_init.nim"
      #- "nim -r c ./tests/test_closure_correctness.nim"
      #- "nim -r c ./tests/test_match_instance.nim"

      #- "nim -r js ./benchmarks/basic_dispatch_methods.nim"
      #- "nim -r js ./benchmarks/basic_dispatch_closures.nim"
      #- "nim -r c ./benchmarks/basic_dispatch_methods.nim"
      #- "nim -r c ./benchmarks/basic_dispatch_closures.nim"

default_task: default
log: true
sound: true
notifications: true
