filesets:
  default:
    include:
      - ".watchcode.yaml"
      - "*.nim"
    exclude:
      - ".watchcode.log"
    exclude_gitignore: false
    match_mode: "gitlike"

tasks:
  default:
    fileset: default
    commands:
      #- "nim -r c ./tests/test_basic_2.nim"
      #- "nim -r c ./tests/test_inheritance_chain.nim"
      #- "nim -r c ./tests/test_overload.nim"
      #- "nim -r c ./tests/test_empty_ctor.nim"
      #- "nim -r c ./tests/test_base_calls.nim"
      - "nim -r c ./tests/test_abstract.nim"
      #- "nim -r c ./tests/test_generic_constructor.nim"

      #- "nim -r js ./benchmarks/basic_dispatch_methods.nim"
      #- "nim -r js ./benchmarks/basic_dispatch_closures.nim"
      #- "nim -r c ./benchmarks/basic_dispatch_methods.nim"
      #- "nim -r c ./benchmarks/basic_dispatch_closures.nim"

default_task: default
log: true
sound: true
notifications: true
