filesets:
  default:
    include:
      - ".watchcode.yaml"
      - "*.nim"
    exclude:
      - ".watchcode.log"
    exclude_gitignore: false
    match_mode: "gitlike"

tasks:
  default:
    fileset: default
    commands:
      #- "nim -r c ./tests/test_basic_1.nim"
      #- "nim -r c ./tests/test_inheritance_chain.nim"
      - "nim -r c ./tests/test_overload.nim"

default_task: default
log: true
sound: true
notifications: true
